spring:
  datasource:
    url: jdbc:mariadb://43.200.49.4:3306/nadri_gil
    username: ec2-user
    password: 0109
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace