spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/nadri_gil
    username: root
    password: 000119
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace