spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/nadri_gil
    username: root
    password: 000119
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

cloud:
  aws:
    credentials:
      accessKey:        # AWS IAM AccessKey 적기
      secretKey:    # AWS IAM SecretKey 적기
    s3:
      bucket: nadri-image
    region:
      static: ap-northeast-2
    stack:
      auto: false
    bucket:
      url: https://s3.ap-northeast-2.amazonaws.com/nadri-image